graph TD
    
    subgraph Clients[" "]
        QE[⚙️<br>Query<br>Engine]
        ExternalServices[⚙️<br>External<br>Services]
    end

    subgraph Polaris ["Polaris"]
        subgraph Core ["Core"]
            RBAC[RBAC]
        end
        subgraph OMS ["Operational Metrics System"]
            Registry[Registry]
            MetricsAPI[API]
            SPI["SPI"]
        end
    end

    subgraph Other[" "]
        MetricsDb[(Metrics<br>Database)]
    end

    QE -->|Pushes new<br>metrics| MetricsAPI
    QE --> |Reads supported<br>metrics|Registry
    ExternalServices --> |Reads supported<br>metrics|Registry
    ExternalServices -->|Fetches<br>metrics| MetricsAPI
    MetricsAPI --> SPI
    MetricsAPI --> |Checks<br>permission| RBAC
    SPI --> MetricsDb
    
    style Polaris stroke-dasharray: 5 5
    style Clients fill:#ffffff,stroke:#ffffff
    style Other fill:#ffffff,stroke:#ffffff

    style OMS stroke:#666,stroke-width:2px
    style QE fill:#e1f5fe
    style ExternalServices fill:#e1f5fe
    style MetricsAPI fill:#f3e5f5

